INSERT INTO `config_estados` ( `short_name`, `name`) VALUES ( 'AC', 'Acre');
INSERT INTO `config_estados` ( `short_name`, `name`) VALUES ( 'AL', 'Alagoas');
INSERT INTO `config_estados` ( `short_name`, `name`) VALUES ( 'AM', 'Amazonas');
INSERT INTO `config_estados` ( `short_name`, `name`) VALUES ( 'AP', 'Amapá');
INSERT INTO `config_estados` ( `short_name`, `name`) VALUES ( 'BA', 'Bahia');
INSERT INTO `config_estados` ( `short_name`, `name`) VALUES ( 'CE', 'Ceará');
INSERT INTO `config_estados` ( `short_name`, `name`) VALUES ( 'DF', 'Distrito Federal');
INSERT INTO `config_estados` ( `short_name`, `name`) VALUES ( 'ES', 'Espirito Santo');
INSERT INTO `config_estados` ( `short_name`, `name`) VALUES ( 'GO', 'Goiás');
INSERT INTO `config_estados` ( `short_name`, `name`) VALUES ( 'MA', 'Maranhão');
INSERT INTO `config_estados` ( `short_name`, `name`) VALUES ( 'MG', 'Minas Gerais');
INSERT INTO `config_estados` ( `short_name`, `name`) VALUES ( 'MS', 'Mato Grosso do Sul');
INSERT INTO `config_estados` ( `short_name`, `name`) VALUES ( 'MT', 'Mato Grosso');
INSERT INTO `config_estados` ( `short_name`, `name`) VALUES ( 'PA', 'Pará');
INSERT INTO `config_estados` ( `short_name`, `name`) VALUES ( 'PB', 'Paraíba');
INSERT INTO `config_estados` ( `short_name`, `name`) VALUES ( 'PE', 'Pernambuco');
INSERT INTO `config_estados` ( `short_name`, `name`) VALUES ( 'PI', 'Piauí');
INSERT INTO `config_estados` ( `short_name`, `name`) VALUES ( 'PR', 'Paraná');
INSERT INTO `config_estados` ( `short_name`, `name`) VALUES ( 'RJ', 'Rio de Janeiro');
INSERT INTO `config_estados` ( `short_name`, `name`) VALUES ( 'RN', 'Rio Grande do Norte');
INSERT INTO `config_estados` ( `short_name`, `name`) VALUES ( 'RO', 'Rondônia');
INSERT INTO `config_estados` ( `short_name`, `name`) VALUES ( 'RR', 'Roraima');
INSERT INTO `config_estados` ( `short_name`, `name`) VALUES ( 'RS', 'Rio Grande do Sul');
INSERT INTO `config_estados` ( `short_name`, `name`) VALUES ( 'SC', 'Santa Catarina');
INSERT INTO `config_estados` ( `short_name`, `name`) VALUES ( 'SE', 'Sergipe');
INSERT INTO `config_estados` ( `short_name`, `name`) VALUES ( 'SP', 'São Paulo');
INSERT INTO `config_estados` ( `short_name`, `name`) VALUES ( 'TO', 'Tocantins');
